export default {
	OK_REQUEST: 'OK_REQUEST',
	UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',

	INVALID_REQUEST: 'INVALID_REQUEST',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

	ROUTER_NOT_FOUND: 'ROUTER_NOT_FOUND',

	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	TOKEN_INVALID: 'TOKEN_INVALID',

	AUTHENTICATION_FAILED: 'Authentication failed. {{context}} not found.',
	AUTHENTICATION_FAILED_PASSWORD: 'Authentication failed. Wrong password.',

	RESTAURANT_CREATED_SUCCESS: 'RESTAURANT_CREATE_SUCCESS',
	RESTAURANT_UPDATED_SUCCESS: 'RESTAURANT_UPDATED_SUCCESS',
	RESTAURANT_DELETED_SUCCESS: 'RESTAURANT_DELETED_SUCCESS',
	RESTAURANT_CREATING_ERROR: 'RESTAURANT_CREATING_ERROR',
	RESTAURANT_UPDATING_ERROR: 'RESTAURANT_UPDATING_ERROR',
	RESTAURANT_DELETING_ERROR: 'RESTAURANT_DELETING_ERROR',

	MENU_CREATED_SUCCESS: 'MENU_CREATE_SUCCESS',
	MENU_UPDATED_SUCCESS: 'MENU_UPDATED_SUCCESS',
	MENU_DELETED_SUCCESS: 'MENU_DELETED_SUCCESS',
	MENU_CREATING_ERROR: 'MENU_CREATING_ERROR',
	MENU_UPDATING_ERROR: 'MENU_UPDATING_ERROR',
	MENU_DELETING_ERROR: 'MENU_DELETING_ERROR',
}
